name: Render Remotion Video

on:
  workflow_dispatch:
    inputs:
      videoName:
        description: 'Nome do vídeo'
        required: true
        type: string
      tipo:
        description: 'Tipo de render'
        required: true
        type: string
      duracao:
        description: 'Duração em segundos'
        required: true
        type: number

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Render video on Lambda
        run: |
          echo "🎥 Iniciando renderização"
          echo "Nome: ${{ github.event.inputs.videoName }}"
          echo "Tipo: ${{ github.event.inputs.tipo }}"
          echo "Duração: ${{ github.event.inputs.duracao }}s"
          npx remotion lambda render src/index.tsx \
            --composition=main \
            --codec=h264 \
            --image-format=jpeg \
            --props='{
              "videoName": "${{ github.event.inputs.videoName }}",
              "tipo": "${{ github.event.inputs.tipo }}",
              "duracao": ${{ github.event.inputs.duracao }}
            }'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
