name: Render Remotion Video

on:
  workflow_dispatch:
    inputs:
      composition:
        description: 'Composition ID'
        required: true
      videoName:
        description: 'Nome do vídeo'
        required: true
      tipo:
        description: 'Tipo do vídeo'
        required: true
      duracao:
        description: 'Duração'
        required: true
      serveUrl:
        description: 'URL de onde o projeto está hospedado'
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Render video
        run: |
          echo "🎬 Iniciando renderização"
          echo "Nome: ${{ github.event.inputs.videoName }}"
          echo "Tipo: ${{ github.event.inputs.tipo }}"
          echo "Duração: ${{ github.event.inputs.duracao }}"
          echo "Composition: ${{ github.event.inputs.composition }}"
          echo "Serve URL: ${{ github.event.inputs.serveUrl }}"

          npx remotion lambda render \
            "${{ github.event.inputs.serveUrl }}" \
            "${{ github.event.inputs.composition }}" \
            --input-props='{
              "videoName": "${{ github.event.inputs.videoName }}",
              "tipo": "${{ github.event.inputs.tipo }}",
              "duracao": ${{ github.event.inputs.duracao }}
            }'
