name: Render Remotion Lambda

on:
  workflow_dispatch:
    inputs:
      videoName:
        description: 'Nome do vídeo'
        required: true
        default: 'video01'
      tipo:
        description: 'Tipo do vídeo'
        required: true
        default: 'normal'
      duracao:
        description: 'Duração (em segundos)'
        required: true
        default: '30'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Render video on Lambda
        run: |
          echo "🎬 Iniciando renderização"
          echo "Nome: ${{ inputs.videoName }}"
          echo "Tipo: ${{ inputs.tipo }}"
          echo "Duração: ${{ inputs.duracao }}"
          echo "Composição: MeuVideo"
          echo "Serve URL: https://remotion-edit.vercel.app/"

          npx remotion lambda render https://remotion-edit.vercel.app MeuVideo out/${{ inputs.videoName }}.mp4 \
            --input-props "{\"videoName\":\"${{ inputs.videoName }}\",\"tipo\":\"${{ inputs.tipo }}\",\"duracao\":${{ inputs.duracao }}}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
