name: Render Remotion Lambda

on:
  workflow_dispatch:
    inputs:
      videoName:
        description: 'Nome do vídeo'
        required: true
        default: 'video01'
      tipo:
        description: 'Tipo do vídeo'
        required: true
        default: 'normal'
      duracao:
        description: 'Duração (em segundos)'
        required: true
        default: '30'
      serveUrl:
        description: 'URL do projeto Remotion'
        required: true
        default: 'https://remotion-edit.vercel.app'
      composition:
        description: 'ID da composição (ex: MeuVideo)'
        required: true
        default: 'MeuVideo'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Render video on Lambda
        run: |
          echo "🎬 Iniciando renderização"
          echo "Nome: ${{ inputs.videoName }}"
          echo "Tipo: ${{ inputs.tipo }}"
          echo "Duração: ${{ inputs.duracao }}"
          echo "Composição: ${{ inputs.composition }}"
          echo "Serve URL: ${{ inputs.serveUrl }}"

          npx remotion lambda render ${{ inputs.serveUrl }} ${{ inputs.composition }} out/${{ inputs.videoName }}.mp4 \
            --region ${{ secrets.REMOTION_AWS_REGION }} \
            --input-props "{\"videoName\":\"${{ inputs.videoName }}\",\"tipo\":\"${{ inputs.tipo }}\",\"duracao\":${{ inputs.duracao }}}"
        env:
          REMOTION_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REMOTION_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REMOTION_AWS_REGION: ${{ secrets.REMOTION_AWS_REGION }}
          REMOTION_AWS_BUCKET_NAME: ${{ secrets.REMOTION_AWS_BUCKET_NAME }}

